server:
  port: 8080
  address: 0.0.0.0 # Allows access from any IP address

spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/chatapp
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: admin123

jwt:
  secret: your-256-bit-secret
  expiration: 86400000  # 24 hours in milliseconds

websocket:
  endpoint: /ws
  destination-prefix: /topic
  application-prefix: /app
