# Configuración para despliegue en producción
# Archivo: application-prod.yml

server:
  port: ${PORT:8080}
  address: 0.0.0.0

spring:
  data:
    redis:
      url: ${REDIS_URL:rediss://default:AZQ_AAIjcDFkZWQxNzQ1MTY5YWY0YzZjYjFkNjhjMDA0MzU1NTNiZXAxMA@hardy-man-37951.upstash.io:6379}
  
  # Configuración de base de datos externa para producción
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/chatapp}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-change-this-in-production}
  expiration: ${JWT_EXPIRATION:86400000}

websocket:
  endpoint: /ws
  destination-prefix: /topic
  application-prefix: /app

# Configuración de CORS para producción
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://your-frontend-domain.vercel.app}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600
