
server:
  port: 8081
  address: 0.0.0.0 # Allows access from any IP address

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      url: rediss://default:AZQ_AAIjcDFkZWQxNzQ1MTY5YWY0YzZjYjFkNjhjMDA0MzU1NTNiZXAxMA@hardy-man-37951.upstash.io:6379
  datasource:
    url: jdbc:postgresql://localhost:5432/chatapp
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: your-256-bit-secret
  expiration: 86400000  # 24 hours in milliseconds

websocket:
  endpoint: /ws
  destination-prefix: /topic
  application-prefix: /app
